export { default as MyButton } from './MyButton'
export { default as MyCheckbox } from './MyCheckbox'
export { default as MyDial } from './MyDial'
export { default as MyRadio } from './MyRadio'
export { default as MySlider } from './MySlider'
export { default as MyTable } from './MyTable'